language: python
python:
    - "3.5"
install: pip install -r Server/Code/requirements.txt
script: py.test
services:
    - mysql
    - redis-server
before_script:
    - mysql -e 'create database unrealknights;'
